# Applies the simple knife-edge slicing method to the length based MEDITS
# data (saved as a *.csv file that was generated by the LFD.R script).

# Copyright Laurence Kell, Alexander Kell, Finlay Scott, Graham Pilling,
# Valerio Bartolino, Chato Osio, Max Cardinale (2015)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#--------------------------------------------------------------------------

# Simple example of slicing the Medits data with the knife edge slicing 
# function data to prepare the age-based indices.

# This script assumes that you have already generated the length based index csv tables using LFD.R

# Libraries, functions and directories
library(plyr)
library(ggplot2)
source("../slicing/length_slicing_funcs.R")
# Where did you put your length based CSV files?
tabdir <- "../../../medits_test/tables/"

# Read in your length based data from the LFD.R script
# Example using MER MER in GSA 9
len_data <- read.csv(paste0(tabdir,"stratified_Nlen_MERL_MER_all_GSA9.csv"), header=TRUE)

# Take a look, is this your data?
head(len_data)

# Set the VB parameters in this format
vB <- c(Linf = 130, K = 0.2, t0 = -0.01)

# The knife-edge slicing gives you the age at beginning of the year.
# It is therefore important to consider when the MEDITS data was collected.
# Add a new column for timing based on month.
# e.g. month = 6,  timing = 0.5
len_data$timing = len_data$month/12

# Set the minimum age and plusgroup
minage <- 1
plusGroup <- 10

# We need to adjust the length to be the middle of the bin
# Here the bin is 5 cm so we add 2.5 cm to the lengths
len_data$min_len <- len_data$len + 2.5

# Slice by year and timing
age_data <- ddply(len_data, .(year, timing), function(x) {
      knife_edge(x[,c("min_len","value")], vB, timing = x$timing[1], plusGroup=plusGroup, minage=minage)
})

head(age_data)

# Now sum over timing (which is now redundant)
age_data <- ddply(age_data, .(year, age), summarise, data = sum(data))

# Take a look by plotting by age
ggplot(age_data, aes(x = age, y=data)) + geom_bar(stat="identity") + facet_wrap(~year)

# Now put this into an FLIndex for use with your assessment
library(FLCore)
flq <- as.FLQuant(age_data)
idx <- FLIndex(index=flq)

# Done
